a= int(input("Enter First Namber:"))
b= int(input("Enter Second Namber:"))
print("Addition (a+b):",a+b)
print("Subtraction (a-b):",a-b)
print("Multiplication (a*b):",a*b)
print("Normal Divisio (a/b):",a/b)
print("Modules/Remainder (a % b):",a%b)
print("Floor Divition (a//b):",a//b)
print("Exponentietion/Power(a**b):",a**b)
